package Views;

/**
 * @author augustosimionato
 */
public class MenuView extends javax.swing.JFrame {

    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        GoOrders = new javax.swing.JButton();
        GoMenu = new javax.swing.JButton();
        GoManEmployees = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("Pizzaria Augusta's");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 40, 150, 23);

        GoOrders.setText("Área de pedidos");
        GoOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoOrdersActionPerformed(evt);
            }
        });
        getContentPane().add(GoOrders);
        GoOrders.setBounds(190, 110, 220, 40);

        GoMenu.setText("Cardápio");
        GoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoMenuActionPerformed(evt);
            }
        });
        getContentPane().add(GoMenu);
        GoMenu.setBounds(190, 170, 220, 40);

        GoManEmployees.setText("Gerenciamento de Funcionários");
        GoManEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoManEmployeesActionPerformed(evt);
            }
        });
        getContentPane().add(GoManEmployees);
        GoManEmployees.setBounds(190, 230, 220, 40);

        setSize(new java.awt.Dimension(590, 383));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GoOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoOrdersActionPerformed
        new OrderView().setVisible(true);
    }//GEN-LAST:event_GoOrdersActionPerformed

    private void GoManEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoManEmployeesActionPerformed
        new EmployeeView().setVisible(true);
    }//GEN-LAST:event_GoManEmployeesActionPerformed

    private void GoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoMenuActionPerformed
        new PizzaView().setVisible(true);
    }//GEN-LAST:event_GoMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoManEmployees;
    private javax.swing.JButton GoMenu;
    private javax.swing.JButton GoOrders;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
